"""LLM Inference Analyzer — web wrapper.

Serves cached analysis reports generated by the llm-inference-analyzer skill
(read-only dependency: skills/llm-inference-analyzer/scripts/main.py) and lets
logged-in users (HF OAuth) generate missing ones.

Env:
  HF_OAUTH_CLIENT_ID / HF_OAUTH_CLIENT_SECRET  — HF OAuth app credentials
  BASE_URL          — public base URL, e.g. https://analyzer.example.com
  SESSION_SECRET    — cookie signing key (required in production)
  DEV_MODE=1        — skip OAuth, auto-login as "dev" (local testing only)
  ADMIN_USERS       — comma-separated HF usernames allowed to view /stats
                      (unset = any logged-in user)
  MAX_REPORTS       — LRU cap on cached reports (default 500)
  GENERATES_PER_HOUR — per-user rate limit (default 20)
"""

import json
import os
import re
import secrets
import sqlite3
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware

WEBAPP_DIR = Path(__file__).resolve().parent
REPO_ROOT = WEBAPP_DIR.parent
SKILL_SCRIPT = REPO_ROOT / "skills" / "llm-inference-analyzer" / "scripts" / "main.py"
DATA_DIR = WEBAPP_DIR / "data"
REPORTS_DIR = DATA_DIR / "reports"
DB_PATH = DATA_DIR / "app.db"

DEV_MODE = os.environ.get("DEV_MODE") == "1"
BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000").rstrip("/")
MAX_REPORTS = int(os.environ.get("MAX_REPORTS", "500"))
GENERATES_PER_HOUR = int(os.environ.get("GENERATES_PER_HOUR", "20"))
GENERATE_TIMEOUT_S = 300

MODEL_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,95}/[A-Za-z0-9][A-Za-z0-9_.-]{0,95}$")
LANGS = ("zh", "en")

app = FastAPI(title="LLM Inference Analyzer")
app.add_middleware(
    SessionMiddleware,
    secret_key=os.environ.get("SESSION_SECRET") or secrets.token_hex(32),
    same_site="lax",
    https_only=BASE_URL.startswith("https://"),
)
templates = Jinja2Templates(directory=str(WEBAPP_DIR / "templates"))


# ---------- storage ----------

def db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with db() as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS reports(
              slug TEXT PRIMARY KEY,
              model_id TEXT NOT NULL,
              lang TEXT NOT NULL,
              created_at TEXT NOT NULL,
              created_by TEXT NOT NULL,
              size_bytes INTEGER NOT NULL,
              last_access TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS access_log(
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              ts TEXT NOT NULL,
              username TEXT NOT NULL,
              action TEXT NOT NULL,
              model_id TEXT
            );
            """
        )


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def log_access(username: str, action: str, model_id: str | None = None) -> None:
    with db() as conn:
        conn.execute(
            "INSERT INTO access_log(ts, username, action, model_id) VALUES(?,?,?,?)",
            (now(), username, action, model_id),
        )


def slug_for(model_id: str, lang: str) -> str:
    return model_id.lower().replace("/", "--") + f".{lang}"


def evict_lru() -> None:
    with db() as conn:
        rows = conn.execute(
            "SELECT slug FROM reports ORDER BY last_access DESC"
        ).fetchall()
        for row in rows[MAX_REPORTS:]:
            (REPORTS_DIR / f"{row['slug']}.html").unlink(missing_ok=True)
            conn.execute("DELETE FROM reports WHERE slug=?", (row["slug"],))


# ---------- auth ----------

def current_user(request: Request) -> str | None:
    if DEV_MODE:
        return "dev"
    return request.session.get("username")


def require_user(request: Request) -> str:
    user = current_user(request)
    if not user:
        raise HTTPException(401, "login required")
    return user


@app.get("/login")
async def login(request: Request, next: str = "/"):
    if DEV_MODE:
        return RedirectResponse("/")
    client_id = os.environ.get("HF_OAUTH_CLIENT_ID")
    if not client_id:
        raise HTTPException(500, "HF_OAUTH_CLIENT_ID not configured")
    state = secrets.token_urlsafe(16)
    request.session["oauth_state"] = state
    # only same-site paths, to avoid open-redirect
    request.session["after_login"] = next if next.startswith("/") and not next.startswith("//") else "/"
    params = httpx.QueryParams(
        client_id=client_id,
        redirect_uri=f"{BASE_URL}/auth/callback",
        response_type="code",
        scope="openid profile",
        state=state,
    )
    return RedirectResponse(f"https://huggingface.co/oauth/authorize?{params}")


@app.get("/auth/callback")
async def auth_callback(request: Request, code: str = "", state: str = ""):
    if not code or state != request.session.pop("oauth_state", None):
        raise HTTPException(400, "bad oauth state")
    async with httpx.AsyncClient(timeout=20) as client:
        token_resp = await client.post(
            "https://huggingface.co/oauth/token",
            data={
                "client_id": os.environ["HF_OAUTH_CLIENT_ID"],
                "client_secret": os.environ["HF_OAUTH_CLIENT_SECRET"],
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": f"{BASE_URL}/auth/callback",
            },
        )
        token_resp.raise_for_status()
        access_token = token_resp.json()["access_token"]
        userinfo = await client.get(
            "https://huggingface.co/oauth/userinfo",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        userinfo.raise_for_status()
    username = userinfo.json().get("preferred_username") or userinfo.json()["sub"]
    request.session["username"] = username
    log_access(username, "login")
    return RedirectResponse(request.session.pop("after_login", "/"))


@app.get("/logout")
async def logout(request: Request):
    request.session.clear()
    return RedirectResponse("/")


# ---------- generation tasks ----------

executor = ThreadPoolExecutor(max_workers=2)
tasks: dict[str, dict] = {}  # task_id -> {status, slug, error, model_id, lang}
tasks_lock = threading.Lock()
rate: dict[str, list[float]] = {}


def check_rate(username: str) -> None:
    cutoff = time.time() - 3600
    stamps = [t for t in rate.get(username, []) if t > cutoff]
    if len(stamps) >= GENERATES_PER_HOUR:
        raise HTTPException(429, f"rate limit: {GENERATES_PER_HOUR} generates/hour")
    stamps.append(time.time())
    rate[username] = stamps


def run_generation(task_id: str, model_id: str, lang: str, username: str) -> None:
    slug = slug_for(model_id, lang)
    out_path = REPORTS_DIR / f"{slug}.html"
    tmp_path = REPORTS_DIR / f".{slug}.tmp.html"
    with tasks_lock:
        tasks[task_id]["status"] = "running"
    try:
        proc = subprocess.run(
            [sys.executable, str(SKILL_SCRIPT), model_id,
             "--html", str(tmp_path), "--lang", lang],
            capture_output=True, text=True, timeout=GENERATE_TIMEOUT_S,
            cwd=str(SKILL_SCRIPT.parent),
        )
        if proc.returncode != 0 or not tmp_path.exists():
            tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-8:]
            raise RuntimeError("\n".join(tail) or f"exit code {proc.returncode}")
        tmp_path.replace(out_path)
        with db() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO reports"
                "(slug, model_id, lang, created_at, created_by, size_bytes, last_access)"
                " VALUES(?,?,?,?,?,?,?)",
                (slug, model_id, lang, now(), username, out_path.stat().st_size, now()),
            )
        evict_lru()
        with tasks_lock:
            tasks[task_id].update(status="done", slug=slug)
    except Exception as exc:  # noqa: BLE001 — task boundary, surface to poller
        tmp_path.unlink(missing_ok=True)
        with tasks_lock:
            tasks[task_id].update(status="failed", error=str(exc)[:2000])


@app.post("/api/generate")
async def api_generate(request: Request):
    username = require_user(request)
    body = await request.json()
    model_id = (body.get("model_id") or "").strip()
    lang = body.get("lang", "zh")
    force = bool(body.get("force"))
    if not MODEL_ID_RE.match(model_id):
        raise HTTPException(400, "invalid model id (expected org/name)")
    if lang not in LANGS:
        raise HTTPException(400, "lang must be zh or en")

    slug = slug_for(model_id, lang)
    if not force and (REPORTS_DIR / f"{slug}.html").exists():
        return {"status": "cached", "slug": slug}

    # reject nonexistent/gated repos before queueing
    async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
        resp = await client.head(f"https://huggingface.co/{model_id}/raw/main/config.json")
    if resp.status_code in (401, 403, 404):
        # HF returns 401 for both nonexistent and gated repos
        raise HTTPException(
            404, f"model {model_id}: not found on huggingface.co, or gated (gated models are not supported)"
        )
    if resp.status_code != 200:
        raise HTTPException(502, f"huggingface.co returned {resp.status_code}")

    check_rate(username)
    log_access(username, "generate", model_id)

    with tasks_lock:
        for tid, t in tasks.items():
            if t["model_id"] == model_id and t["lang"] == lang and t["status"] in ("pending", "running"):
                return {"status": "queued", "task_id": tid}
        task_id = secrets.token_urlsafe(8)
        tasks[task_id] = {"status": "pending", "model_id": model_id, "lang": lang,
                          "slug": None, "error": None}
    executor.submit(run_generation, task_id, model_id, lang, username)
    return {"status": "queued", "task_id": task_id}


@app.get("/api/tasks/{task_id}")
async def api_task(task_id: str):
    with tasks_lock:
        t = tasks.get(task_id)
        if not t:
            raise HTTPException(404, "unknown task")
        return dict(t)


LOGIN_GATE_HTML = """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Login required</title>
<style>
  body{margin:0;background:#f9f9f7;color:#0b0b0b;font:14px/1.6 system-ui,-apple-system,"PingFang SC",sans-serif;
    display:flex;align-items:center;justify-content:center;min-height:100vh}
  @media (prefers-color-scheme:dark){body{background:#0d0d0d;color:#fff}}
  .box{text-align:center;padding:32px}
  a.btn{display:inline-block;margin-top:16px;padding:10px 22px;border-radius:10px;
    background:#0b0b0b;color:#f9f9f7;text-decoration:none;font-weight:600}
  @media (prefers-color-scheme:dark){a.btn{background:#fff;color:#0d0d0d}}
  p{color:#898781;margin:6px 0 0}
</style></head><body><div class="box">
  <div style="font-size:18px;font-weight:600">需要登录 / Login required</div>
  <p>查看报告需要 Hugging Face 登录 · Viewing reports requires signing in with Hugging Face</p>
  <a class="btn" href="/login?next={next}">使用 Hugging Face 登录 · Sign in</a>
</div></body></html>"""


# ---------- pages & report data ----------

@app.get("/api/reports")
async def api_reports():
    with db() as conn:
        rows = conn.execute(
            "SELECT slug, model_id, lang, created_at, created_by, size_bytes,"
            " (SELECT COUNT(*) FROM access_log a"
            "   WHERE a.action='view' AND a.model_id = reports.model_id) AS views"
            " FROM reports ORDER BY created_at DESC"
        ).fetchall()
    return [dict(r) for r in rows]


@app.get("/reports/{slug}.html")
async def serve_report(request: Request, slug: str):
    if not re.match(r"^[a-z0-9_.-]+$", slug):
        raise HTTPException(400, "bad slug")
    username = current_user(request)
    if not username:
        # interstitial instead of auto-redirect: HF silently re-authorizes
        # already-approved apps, so an automatic bounce would undo /logout
        return HTMLResponse(LOGIN_GATE_HTML.replace("{next}", f"/reports/{slug}.html"),
                            status_code=401)
    path = REPORTS_DIR / f"{slug}.html"
    if not path.exists():
        raise HTTPException(404, "no such report")
    with db() as conn:
        row = conn.execute("SELECT model_id FROM reports WHERE slug=?", (slug,)).fetchone()
        conn.execute("UPDATE reports SET last_access=? WHERE slug=?", (now(), slug))
    log_access(username, "view", row["model_id"] if row else slug)
    return FileResponse(path, media_type="text/html")


@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse(request, "index.html", {
        "username": current_user(request),
        "dev_mode": DEV_MODE,
    })


@app.get("/stats")
async def stats(request: Request):
    username = require_user(request)
    admins = [u.strip() for u in os.environ.get("ADMIN_USERS", "").split(",") if u.strip()]
    if admins and username not in admins:
        raise HTTPException(403, "admins only")
    with db() as conn:
        users = conn.execute(
            "SELECT username, COUNT(*) n, MAX(ts) last_seen FROM access_log"
            " GROUP BY username ORDER BY n DESC"
        ).fetchall()
        actions = conn.execute(
            "SELECT action, COUNT(*) n FROM access_log GROUP BY action"
        ).fetchall()
        recent = conn.execute(
            "SELECT ts, username, action, model_id FROM access_log"
            " ORDER BY id DESC LIMIT 50"
        ).fetchall()
    return JSONResponse({
        "users": [dict(r) for r in users],
        "actions": [dict(r) for r in actions],
        "recent": [dict(r) for r in recent],
    })


init_db()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "8000")))
