"""LLM Inference Analyzer — web wrapper.

Serves cached analysis reports generated by the bundled analyzer
(webapp/analyzer/main.py — also importable in-process as the compute engine)
and lets logged-in users (HF OAuth) generate missing ones.

Env:
  HF_OAUTH_CLIENT_ID / HF_OAUTH_CLIENT_SECRET  — HF OAuth app credentials
  BASE_URL          — public base URL, e.g. https://analyzer.example.com
  SESSION_SECRET    — cookie signing key (required in production)
  DEV_MODE=1        — skip OAuth, auto-login as "dev" (local testing only)
  ADMIN_USERS       — comma-separated HF usernames allowed to view /stats
                      (unset = any logged-in user)
  MAX_REPORTS       — LRU cap on cached reports (default 500)
  GENERATES_PER_HOUR — per-user rate limit (default 20)
"""

import json
import os
import re
import secrets
import sqlite3
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path

import httpx
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from starlette.middleware.sessions import SessionMiddleware

WEBAPP_DIR = Path(__file__).resolve().parent
REPO_ROOT = WEBAPP_DIR.parent
ANALYZER_SCRIPT = WEBAPP_DIR / "analyzer" / "main.py"

# in-process import of the compute engine (same sources the subprocess uses)
sys.path.insert(0, str(ANALYZER_SCRIPT.parent))
import engine  # noqa: E402
import main as core  # noqa: E402
DATA_DIR = WEBAPP_DIR / "data"
REPORTS_DIR = DATA_DIR / "reports"
DB_PATH = DATA_DIR / "app.db"

DEV_MODE = os.environ.get("DEV_MODE") == "1"
BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000").rstrip("/")
MAX_REPORTS = int(os.environ.get("MAX_REPORTS", "500"))
GENERATES_PER_HOUR = int(os.environ.get("GENERATES_PER_HOUR", "20"))
GENERATE_TIMEOUT_S = 300

MODEL_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,95}/[A-Za-z0-9][A-Za-z0-9_.-]{0,95}$")

app = FastAPI(title="LLM Inference Analyzer")
app.add_middleware(
    SessionMiddleware,
    secret_key=os.environ.get("SESSION_SECRET") or secrets.token_hex(32),
    same_site="lax",
    https_only=BASE_URL.startswith("https://"),
)
templates = Jinja2Templates(directory=str(WEBAPP_DIR / "templates"))


# ---------- storage ----------

def db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with db() as conn:
        conn.executescript(
            """
            CREATE TABLE IF NOT EXISTS reports(
              slug TEXT PRIMARY KEY,
              model_id TEXT NOT NULL,
              created_at TEXT NOT NULL,
              created_by TEXT NOT NULL,
              size_bytes INTEGER NOT NULL,
              last_access TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS access_log(
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              ts TEXT NOT NULL,
              username TEXT NOT NULL,
              action TEXT NOT NULL,
              model_id TEXT
            );
            """
        )
        cols = [r["name"] for r in conn.execute("PRAGMA table_info(reports)")]
        if "report_version" not in cols:
            conn.execute("ALTER TABLE reports ADD COLUMN report_version TEXT")
        if "lang" in cols:
            _migrate_langless(conn)


def _migrate_langless(conn: sqlite3.Connection) -> None:
    """One-time: reports were cached per (model, lang); the page has a built-in
    language switcher, so the lang axis is gone. Keep one report per model
    (zh preferred — it's just the first-paint language), rename `<slug>.zh`
    files to `<slug>`, drop the rest."""
    rows = conn.execute("SELECT slug, model_id, lang FROM reports").fetchall()
    keep: dict[str, sqlite3.Row] = {}
    for r in rows:
        cur = keep.get(r["model_id"])
        if cur is None or (r["lang"] == "zh" and cur["lang"] != "zh"):
            keep[r["model_id"]] = r
    for r in rows:
        old = REPORTS_DIR / f"{r['slug']}.html"
        if keep.get(r["model_id"]) is r:
            new = REPORTS_DIR / f"{slug_for(r['model_id'])}.html"
            if old.exists():
                old.replace(new)
        else:
            old.unlink(missing_ok=True)
    conn.execute("ALTER TABLE reports RENAME TO reports_old")
    conn.execute(
        """CREATE TABLE reports(
             slug TEXT PRIMARY KEY, model_id TEXT NOT NULL,
             created_at TEXT NOT NULL, created_by TEXT NOT NULL,
             size_bytes INTEGER NOT NULL, last_access TEXT NOT NULL,
             report_version TEXT)"""
    )
    for r in keep.values():
        conn.execute(
            "INSERT INTO reports SELECT ?, model_id, created_at, created_by,"
            " size_bytes, last_access, report_version FROM reports_old WHERE slug=?",
            (slug_for(r["model_id"]), r["slug"]),
        )
    conn.execute("DROP TABLE reports_old")


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def log_access(username: str, action: str, model_id: str | None = None) -> None:
    with db() as conn:
        conn.execute(
            "INSERT INTO access_log(ts, username, action, model_id) VALUES(?,?,?,?)",
            (now(), username, action, model_id),
        )


def slug_for(model_id: str) -> str:
    return model_id.lower().replace("/", "--")


def evict_lru() -> None:
    with db() as conn:
        rows = conn.execute(
            "SELECT slug FROM reports ORDER BY last_access DESC"
        ).fetchall()
        for row in rows[MAX_REPORTS:]:
            (REPORTS_DIR / f"{row['slug']}.html").unlink(missing_ok=True)
            conn.execute("DELETE FROM reports WHERE slug=?", (row["slug"],))


# ---------- auth ----------

def current_user(request: Request) -> str | None:
    if DEV_MODE:
        return "dev"
    return request.session.get("username")


def require_user(request: Request) -> str:
    user = current_user(request)
    if not user:
        raise HTTPException(401, "login required")
    return user


@app.get("/login")
async def login(request: Request, next: str = "/"):
    if DEV_MODE:
        return RedirectResponse("/")
    client_id = os.environ.get("HF_OAUTH_CLIENT_ID")
    if not client_id:
        raise HTTPException(500, "HF_OAUTH_CLIENT_ID not configured")
    state = secrets.token_urlsafe(16)
    request.session["oauth_state"] = state
    # only same-site paths, to avoid open-redirect
    request.session["after_login"] = next if next.startswith("/") and not next.startswith("//") else "/"
    params = httpx.QueryParams(
        client_id=client_id,
        redirect_uri=f"{BASE_URL}/auth/callback",
        response_type="code",
        scope="openid profile",
        state=state,
    )
    return RedirectResponse(f"https://huggingface.co/oauth/authorize?{params}")


@app.get("/auth/callback")
async def auth_callback(request: Request, code: str = "", state: str = ""):
    if not code or state != request.session.pop("oauth_state", None):
        raise HTTPException(400, "bad oauth state")
    async with httpx.AsyncClient(timeout=20) as client:
        token_resp = await client.post(
            "https://huggingface.co/oauth/token",
            data={
                "client_id": os.environ["HF_OAUTH_CLIENT_ID"],
                "client_secret": os.environ["HF_OAUTH_CLIENT_SECRET"],
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": f"{BASE_URL}/auth/callback",
            },
        )
        token_resp.raise_for_status()
        access_token = token_resp.json()["access_token"]
        userinfo = await client.get(
            "https://huggingface.co/oauth/userinfo",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        userinfo.raise_for_status()
    username = userinfo.json().get("preferred_username") or userinfo.json()["sub"]
    request.session["username"] = username
    log_access(username, "login")
    return RedirectResponse(request.session.pop("after_login", "/"))


@app.get("/logout")
async def logout(request: Request):
    request.session.clear()
    return RedirectResponse("/")


# ---------- generation tasks ----------

executor = ThreadPoolExecutor(max_workers=2)
tasks: dict[str, dict] = {}  # task_id -> {status, slug, error, model_id}
tasks_lock = threading.Lock()
rate: dict[str, list[float]] = {}
rate_lock = threading.Lock()  # mutated from the event loop AND sync worker threads


def check_rate(key: str, per_hour: int = GENERATES_PER_HOUR,
               what: str = "generates") -> None:
    """Sliding-window rate limit shared by all endpoints (key = user or ip)."""
    cutoff = time.time() - 3600
    with rate_lock:
        stamps = [t for t in rate.get(key, []) if t > cutoff]
        if len(stamps) >= per_hour:
            raise HTTPException(429, f"rate limit: {per_hour} {what}/hour")
        stamps.append(time.time())
        rate[key] = stamps
        if len(rate) > 10_000:  # prune long-dead keys (one-off IPs)
            for k in [k for k, v in rate.items() if not v or v[-1] < cutoff]:
                del rate[k]


def run_generation(task_id: str, model_id: str, username: str) -> None:
    slug = slug_for(model_id)
    out_path = REPORTS_DIR / f"{slug}.html"
    tmp_path = REPORTS_DIR / f".{slug}.tmp.html"
    with tasks_lock:
        tasks[task_id]["status"] = "running"
    try:
        # --lang only sets the first-paint language; the page has a built-in
        # zh/en switcher (choice persisted in localStorage)
        proc = subprocess.run(
            [sys.executable, str(ANALYZER_SCRIPT), model_id,
             "--html", str(tmp_path), "--lang", "zh"],
            capture_output=True, text=True, timeout=GENERATE_TIMEOUT_S,
            cwd=str(ANALYZER_SCRIPT.parent),
        )
        if proc.returncode != 0 or not tmp_path.exists():
            tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-8:]
            raise RuntimeError("\n".join(tail) or f"exit code {proc.returncode}")
        tmp_path.replace(out_path)
        with db() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO reports"
                "(slug, model_id, created_at, created_by, size_bytes,"
                " last_access, report_version)"
                " VALUES(?,?,?,?,?,?,?)",
                (slug, model_id, now(), username, out_path.stat().st_size,
                 now(), engine.report_version()),
            )
        evict_lru()
        with tasks_lock:
            tasks[task_id].update(status="done", slug=slug)
    except Exception as exc:  # noqa: BLE001 — task boundary, surface to poller
        tmp_path.unlink(missing_ok=True)
        with tasks_lock:
            tasks[task_id].update(status="failed", error=str(exc)[:2000])


@app.post("/api/generate")
async def api_generate(request: Request):
    username = require_user(request)
    body = await request.json()
    model_id = (body.get("model_id") or "").strip()
    force = bool(body.get("force"))
    if not MODEL_ID_RE.match(model_id):
        raise HTTPException(400, "invalid model id (expected org/name)")

    slug = slug_for(model_id)
    if not force and (REPORTS_DIR / f"{slug}.html").exists():
        return {"status": "cached", "slug": slug}

    # reject nonexistent/gated repos before queueing
    async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
        resp = await client.head(f"https://huggingface.co/{model_id}/raw/main/config.json")
    if resp.status_code in (401, 403, 404):
        # HF returns 401 for both nonexistent and gated repos
        raise HTTPException(
            404, f"model {model_id}: not found on huggingface.co, or gated (gated models are not supported)"
        )
    if resp.status_code != 200:
        raise HTTPException(502, f"huggingface.co returned {resp.status_code}")

    check_rate(username)
    log_access(username, "generate", model_id)
    return _queue_report(model_id, username, force=force)


@app.get("/api/tasks/{task_id}")
async def api_task(task_id: str):
    with tasks_lock:
        t = tasks.get(task_id)
        if not t:
            raise HTTPException(404, "unknown task")
        return dict(t)


LOGIN_GATE_HTML = """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Login required</title>
<style>
  body{margin:0;background:#f9f9f7;color:#0b0b0b;font:14px/1.6 system-ui,-apple-system,"PingFang SC",sans-serif;
    display:flex;align-items:center;justify-content:center;min-height:100vh}
  @media (prefers-color-scheme:dark){body{background:#0d0d0d;color:#fff}}
  .box{text-align:center;padding:32px}
  a.btn{display:inline-block;margin-top:16px;padding:10px 22px;border-radius:10px;
    background:#0b0b0b;color:#f9f9f7;text-decoration:none;font-weight:600}
  @media (prefers-color-scheme:dark){a.btn{background:#fff;color:#0d0d0d}}
  p{color:#898781;margin:6px 0 0}
</style></head><body><div class="box">
  <div style="font-size:18px;font-weight:600">需要登录 / Login required</div>
  <p>查看报告需要 Hugging Face 登录 · Viewing reports requires signing in with Hugging Face</p>
  <a class="btn" href="/login?next={next}">使用 Hugging Face 登录 · Sign in</a>
</div></body></html>"""


# ---------- pages & report data ----------

@app.get("/api/reports")
async def api_reports():
    with db() as conn:
        rows = conn.execute(
            "SELECT slug, model_id, created_at, created_by, size_bytes,"
            " (SELECT COUNT(*) FROM access_log a"
            "   WHERE a.action='view' AND a.model_id = reports.model_id) AS views"
            " FROM reports ORDER BY views DESC, created_at DESC"
        ).fetchall()
    return [dict(r) for r in rows]


@app.get("/reports/{slug}.html")
async def serve_report(request: Request, slug: str):
    if not re.match(r"^[a-z0-9_.-]+$", slug):
        raise HTTPException(400, "bad slug")
    username = current_user(request)
    if not username:
        # interstitial instead of auto-redirect: HF silently re-authorizes
        # already-approved apps, so an automatic bounce would undo /logout
        return HTMLResponse(LOGIN_GATE_HTML.replace("{next}", f"/reports/{slug}.html"),
                            status_code=401)
    path = REPORTS_DIR / f"{slug}.html"
    if not path.exists():
        raise HTTPException(404, "no such report")
    with db() as conn:
        row = conn.execute(
            "SELECT model_id, report_version FROM reports WHERE slug=?",
            (slug,)).fetchone()
        conn.execute("UPDATE reports SET last_access=? WHERE slug=?", (now(), slug))
    log_access(username, "view", row["model_id"] if row else slug)
    # stale shell (engine/template updated since generation): serve the old
    # page now, regenerate in the background so the next view is current.
    # The page's dynamic numbers come from /api/v1/whatif and are always
    # current regardless; this refreshes the baked static parts.
    if row and row["report_version"] != engine.report_version():
        _queue_report(row["model_id"], "stale-regen", force=True)
    return FileResponse(path, media_type="text/html")


# ---------- anonymous data API (v1) ----------
#
# Machine-facing, no auth: returns the analysis numbers as JSON so LLM agents
# (the published skill) can answer in chat without bundling the math. Humans
# still view the interactive report through the OAuth-gated /reports/ page —
# the API returns that URL for hand-off. All parameters optional except
# `model`; response echoes every effective assumption.

API_PER_HOUR = int(os.environ.get("API_PER_HOUR", "120"))
MODEL_CACHE_TTL_S = 6 * 3600
KV_DTYPES = ("auto", "bf16", "fp16", "fp8", "fp4")
WEIGHT_DTYPES = ("bf16", "fp8", "fp4")

core.set_lang("en")  # in-process engine output language (subprocess renders keep --lang)
ENGINE_VERSION = engine.engine_version()

# GPU name -> memory GiB, derived from the instance table (max variant per GPU)
GPU_CATALOG: dict[str, float] = {}
for _name, (_gpu, _cnt, _mib) in core.STATIC_INSTANCES.items():
    GPU_CATALOG[_gpu] = max(GPU_CATALOG.get(_gpu, 0), round(_mib / 1024, 1))

_model_cache: dict[str, tuple[float, dict, dict | None, list[str], tuple | None]] = {}
_model_cache_lock = threading.Lock()


def _load_model(model_id: str) -> tuple[dict, dict | None, list[str], tuple | None]:
    """config + safetensors catalog + precomputed exact_components, cached.
    The headers fetch takes seconds, and exact_components over a 100k+-tensor
    MoE catalog takes seconds of CPU — both depend only on the model, so they
    are computed once per cache fill, not per request."""
    with _model_cache_lock:
        hit = _model_cache.get(model_id)
        if hit and time.time() - hit[0] < MODEL_CACHE_TTL_S:
            return hit[1], hit[2], hit[3], hit[4]
    cfg = engine.normalize_config(core.fetch_config(model_id))
    catalog, warnings = None, []
    try:
        catalog, declared, _n_shards, _index_info = core.fetch_safetensors_catalog(model_id)
        got = sum(t["bytes"] for t in catalog.values())
        if declared and abs(got - declared) / declared > 0.01:
            warnings.append(
                f"safetensors headers sum {got / (1024**3):.1f} GiB vs index-declared "
                f"{declared / (1024**3):.1f} GiB — some shards may be unread")
    except Exception as exc:  # noqa: BLE001 — degrade to formula estimate
        warnings.append(f"could not read safetensors headers ({exc}); "
                        "weight numbers are formula estimates")
    exact_parts = core.exact_components(catalog, cfg) if catalog else None
    with _model_cache_lock:
        _model_cache[model_id] = (time.time(), cfg, catalog, warnings, exact_parts)
        if len(_model_cache) > 64:  # bound memory: drop oldest entries
            for k in sorted(_model_cache, key=lambda k: _model_cache[k][0])[:16]:
                _model_cache.pop(k, None)
    return cfg, catalog, warnings, exact_parts


def _resolve_hardware(instance: str | None, gpu: str | None,
                      gpu_mem_gib: float | None, gpus_per_node: int) -> dict:
    """Priority: instance name > GPU name (catalog) > raw memory number."""
    if instance:
        spec = core.STATIC_INSTANCES.get(instance)
        if not spec:
            raise HTTPException(400, f"unknown instance '{instance}'; supported: "
                                     f"{', '.join(core.STATIC_INSTANCES)}")
        g, cnt, mib = spec
        return {"gpu": g, "gpn": cnt, "memGib": round(mib / 1024, 1),
                "label": f"{instance} ({cnt}x{g} {mib / 1024:.0f} GiB)"}
    if gpu:
        name = gpu.strip().upper()
        if name not in GPU_CATALOG:
            raise HTTPException(400, f"unknown GPU '{gpu}'; supported: "
                                     f"{', '.join(sorted(GPU_CATALOG))}. For other "
                                     f"hardware pass gpu_mem_gib=<GiB per GPU> instead")
        mem = gpu_mem_gib or GPU_CATALOG[name]
        return {"gpu": name, "gpn": gpus_per_node, "memGib": mem,
                "label": f"{gpus_per_node}x{name} {mem:g} GiB"}
    if gpu_mem_gib:
        return {"gpu": None, "gpn": gpus_per_node, "memGib": gpu_mem_gib,
                "label": f"custom {gpus_per_node}x{gpu_mem_gib:g} GiB"}
    g, cnt, mib = core.STATIC_INSTANCES["p5en.48xlarge"]
    return {"gpu": g, "gpn": cnt, "memGib": round(mib / 1024, 1),
            "label": f"p5en.48xlarge ({cnt}x{g} {mib / 1024:.0f} GiB) [default]"}


def _queue_report(model_id: str, username: str, force: bool = False) -> dict:
    """Queue default-report generation (dedups against in-flight tasks).
    force=True regenerates even when a (stale) report exists. Returns the
    same {status, ...} shape /api/generate responds with."""
    slug = slug_for(model_id)
    if not force and (REPORTS_DIR / f"{slug}.html").exists():
        return {"status": "cached", "slug": slug}
    with tasks_lock:
        for tid, t in tasks.items():
            if t["model_id"] == model_id and t["status"] in ("pending", "running"):
                return {"status": "queued", "task_id": tid}
        task_id = secrets.token_urlsafe(8)
        tasks[task_id] = {"status": "pending", "model_id": model_id,
                          "slug": None, "error": None}
    executor.submit(run_generation, task_id, model_id, username)
    return {"status": "queued", "task_id": task_id}


def _prepare_analysis(request: Request, *, model: str, context: int, requests: int,
                      kv_dtype: str, tp: int, pp: int, ep: int | None,
                      dp_attention: bool, instance: str | None, gpu: str | None,
                      gpu_mem_gib: float | None, gpus_per_node: int,
                      mem_fraction_static: float, fixed_overhead_gib: float | None,
                      batch_tokens: int, chunk_tokens: int | None,
                      weight_dtype: str | None,
                      rate_prefix: str, rate_limit: int,
                      rate_what: str) -> tuple:
    """Validate + rate-limit + load + analyze — the shared front half of
    /api/v1/analyze and /api/v1/whatif. Returns (a, cfg, D, P, hw,
    weight_warnings). Any rule about resolving parameters into the engine's
    D/P contract lives HERE, once."""
    if not MODEL_ID_RE.match(model):
        raise HTTPException(400, "invalid model id (expected org/name)")
    if kv_dtype not in KV_DTYPES:
        raise HTTPException(400, f"kv_dtype must be one of {KV_DTYPES}")
    if weight_dtype and weight_dtype not in WEIGHT_DTYPES:
        raise HTTPException(400, f"weight_dtype must be one of {WEIGHT_DTYPES}")
    hw = _resolve_hardware(instance, gpu, gpu_mem_gib, gpus_per_node)

    ip = request.client.host if request.client else "unknown"
    check_rate(f"{rate_prefix}:{ip}", rate_limit, rate_what)

    try:
        cfg, catalog, weight_warnings, exact_parts = _load_model(model)
    except Exception as exc:  # noqa: BLE001 — nonexistent/gated/network
        raise HTTPException(
            404, f"cannot fetch {model} from huggingface.co ({exc}); nonexistent or "
                 f"gated models are not supported") from exc

    kv_effective = engine.resolve_kv_auto(cfg) if kv_dtype == "auto" else kv_dtype
    # effective forward size F: chunk_tokens (the chunked-prefill control)
    # wins over the legacy batch_tokens, so runtime.activation_gib and the
    # parallel-tab serving transient agree on the same F
    a = core.analyze(model, cfg, context, requests, kv_effective,
                     chunk_tokens or batch_tokens, 0.05,
                     catalog=catalog, exact_parts=exact_parts)
    # fp4 checkpoints inflate at load: engines materialize scale/dequant
    # side-buffers beyond the packed safetensors bytes. Measured on B200:
    # DSv4-Pro +4.6% whole-model (mxfp4 experts, S1M), DSv4-Flash +12%
    # (mxfp4) to +22% (dequant path, S1). Spread too wide for a silent
    # multiplier — warn instead so fit verdicts near the boundary get a
    # human check.
    if "fp4" in a["wname"]:
        weight_warnings = list(weight_warnings) + [
            "fp4 权重运行时会膨胀（B200 实测 +4.6%~+22%，随 kernel 路径而异）——"
            "safetensors 口径的 weights 偏乐观，贴边的 fit 判定请留余量"]
    D = engine.deploy_data(a, cfg)
    # default fixed overhead is TP-scaled (CUDA context + NCCL buffers grow
    # with world size): 0.65 GiB @TP1 (S0 measured) + 0.265/extra rank
    # (anchors: S1 2.5 GiB @TP8; S1M re-measured 2.90 pre-load @TP8).
    # An explicit fixed_overhead_gib query param still wins.
    fixed_eff = (fixed_overhead_gib if fixed_overhead_gib is not None
                 else round(0.65 + 0.265 * (tp - 1), 2))
    D["fixedGib"] = fixed_eff
    P = {"tp": tp, "pp": pp, "ep": ep or tp,
         "dpAttn": dp_attention and engine.dp_available(D, tp),
         "memGib": hw["memGib"], "gpn": hw["gpn"], "ctx": context, "req": requests,
         "kvDtype": kv_effective, "frac": mem_fraction_static,
         "fixedGib": fixed_eff,
         # forward step size F for the serving-transient estimate: the
         # chunked-prefill-size control drives both the roofline chunk and
         # the parallel tab's activation term
         "chunk": chunk_tokens or batch_tokens}
    return a, cfg, D, P, hw, weight_warnings


@app.get("/api/v1/analyze")
def api_v1_analyze(  # sync def: FastAPI runs it in a worker thread (blocking HF fetches)
    request: Request,
    model: str = Query(..., description="HuggingFace model id, org/name"),
    context: int = Query(131_072, ge=128, le=16_777_216),
    requests: int = Query(16, ge=1, le=65_536),
    kv_dtype: str = Query("auto"),
    tp: int = Query(8, ge=1, le=128),
    pp: int = Query(1, ge=1, le=64),
    ep: int | None = Query(None, ge=1, le=128),
    dp_attention: bool = Query(False),
    instance: str | None = Query(None),
    gpu: str | None = Query(None),
    gpu_mem_gib: float | None = Query(None, gt=0),
    gpus_per_node: int = Query(8, ge=1, le=72),
    mem_fraction_static: float = Query(0.9, ge=0.3, le=0.99),
    fixed_overhead_gib: float | None = Query(None, ge=0, le=16),  # default: TP-scaled 0.65+0.265*(tp-1)
    batch_tokens: int = Query(8192, ge=128, le=131_072),
    chunk_tokens: int | None = Query(None, ge=128, le=131_072),
    weight_dtype: str | None = Query(None, description="roofline what-if override"),
):
    a, cfg, D, P, hw, weight_warnings = _prepare_analysis(
        request, model=model, context=context, requests=requests,
        kv_dtype=kv_dtype, tp=tp, pp=pp, ep=ep, dp_attention=dp_attention,
        instance=instance, gpu=gpu, gpu_mem_gib=gpu_mem_gib,
        gpus_per_node=gpus_per_node, mem_fraction_static=mem_fraction_static,
        fixed_overhead_gib=fixed_overhead_gib, batch_tokens=batch_tokens,
        chunk_tokens=chunk_tokens, weight_dtype=weight_dtype,
        rate_prefix="api", rate_limit=API_PER_HOUR, rate_what="analyses per IP")
    ip = request.client.host if request.client else "unknown"
    log_access(f"api:{ip}", "analyze", model)
    kv_effective, ep_effective, dp_effective = P["kvDtype"], P["ep"], P["dpAttn"]

    parallel = engine.parallel_verdict(D, P)
    sweep = engine.tp_sweep(D, P, hw["gpn"])
    roofline = (engine.roofline_verdict(a, cfg, D, P, hw["gpu"],
                                        chunk_tokens or batch_tokens, weight_dtype)
                if hw["gpu"] else None)

    slug = slug_for(model)
    _queue_report(model, f"api:{ip}")
    gib = 1024 ** 3

    defaults_used = [name for name, given in (
        ("context", context != 131_072), ("requests", requests != 16),
        ("kv_dtype", kv_dtype != "auto"), ("tp", tp != 8), ("pp", pp != 1),
        ("hardware", bool(instance or gpu or gpu_mem_gib)),
        ("mem_fraction_static", mem_fraction_static != 0.9),
    ) if not given]

    return JSONResponse({
        "model": model,
        "architecture": (cfg.get("architectures") or ["?"])[0],
        "engine_version": ENGINE_VERSION,
        "assumptions": {
            "context": context, "concurrent_requests": requests,
            "kv_dtype": kv_effective,
            "kv_dtype_requested": kv_dtype,
            "hardware": hw["label"], "gpu_mem_gib": hw["memGib"],
            "gpus_per_node": hw["gpn"],
            "tp": tp, "pp": pp, "ep": ep_effective,
            "dp_attention": dp_effective,
            "dp_attention_requested": dp_attention,
            "mem_fraction_static": mem_fraction_static,
            "fixed_overhead_gib": P["fixedGib"],  # effective: TP-scaled default unless overridden
            "batch_tokens": batch_tokens,
            "chunk_tokens": chunk_tokens or batch_tokens,
            "defaults_used": defaults_used,
        },
        "weights": {
            "total_gib": round(a["total_bytes"] / gib, 2),
            "total_params_b": round(a["total_params"] / 1e9, 2),
            "dtype": a["wname"],
            "exact_from_safetensors": a["exact"],
            "active_params_b": round(a["active"] / 1e9, 2) if a["active"] else None,
            "components": [
                {"name": c["name"], "params_b": round(c["params"] / 1e9, 3),
                 "gib": round(c["bytes"] / gib, 2), "share": round(c["share"], 4)}
                for c in sorted(a["comps"], key=lambda c: -c["bytes"]) if c["params"]],
            "warnings": weight_warnings,
        },
        "kv_cache": {
            "dtype": kv_effective,
            "per_token_kib": round(a["kv_per_tok"] / 1024, 1),
            "per_request_gib": round(a["kv_per_req"] / gib, 3),
            "total_gib": round(a["kv_total"] / gib, 2),
            "mla_vs_mha_savings_x": round(a["mha_ratio"], 1) if a["mha_ratio"] else None,
            "linear_state_total_gib": round(a["lin_state_total"] / gib, 2)
            if a["lin_state_total"] else 0,
            "notes": a["kv_struct"]["warnings"],
        },
        "runtime": {
            "activation_gib": round(a["act_total"] / gib, 2),
            "vision_encoder_activation_gib": round(a["vision_act"] / gib, 2)
            if a["vision_act"] else 0,
            "runtime_total_gib": round(a["runtime_total"] / gib, 2),
            "grand_total_gib": round(a["grand"] / gib, 2),
            "grand_total_note": "weights + runtime + 5% fragmentation, single-copy "
                                "(no TP replication); use `parallel` for per-GPU fit",
        },
        "parallel": parallel,
        "tp_sweep": {
            "note": f"pp=1 on {hw['label']}; max_concurrency at context={context}",
            "rows": sweep,
        },
        "roofline": roofline or {
            "note": "no compute/bandwidth spec for this hardware; pass a known "
                    f"gpu ({', '.join(sorted(core.GPU_PERF))}) for roofline bounds"},
        "report_url": f"{BASE_URL}/reports/{slug}.html",
        "report_note": "interactive 4-tab report (deep links: #evidence #estimate "
                       "#parallel #roofline; in-page zh/en switcher); requires "
                       "HuggingFace login in a browser; generating in background "
                       "if absent — may take ~1 min on first request",
    })


@app.get("/api/v1/whatif")
def api_v1_whatif(  # sync def: worker thread (config fetch may block on first hit)
    request: Request,
    model: str = Query(...),
    context: int = Query(131_072, ge=128, le=16_777_216),
    requests: int = Query(16, ge=1, le=65_536),
    kv_dtype: str = Query("auto"),
    tp: int = Query(8, ge=1, le=128),
    pp: int = Query(1, ge=1, le=64),
    ep: int | None = Query(None, ge=1, le=128),
    dp_attention: bool = Query(False),
    instance: str | None = Query(None),
    gpu: str | None = Query(None),
    gpu_mem_gib: float | None = Query(None, gt=0),
    gpus_per_node: int = Query(8, ge=1, le=72),
    mem_fraction_static: float = Query(0.9, ge=0.3, le=0.99),
    fixed_overhead_gib: float | None = Query(None, ge=0, le=16),  # default: TP-scaled 0.65+0.265*(tp-1)
    batch_tokens: int = Query(8192, ge=128, le=131_072),
    chunk_tokens: int | None = Query(None, ge=128, le=131_072),
    weight_dtype: str | None = Query(None),
):
    """Render feed for the report page: one parameter combination → the
    numbers all three dynamic tabs need. Same knobs as /api/v1/analyze but
    the response is renderer-shaped (template.js field names) and skips the
    prose/sweep sections. Anonymous; report pages call it same-origin on
    every dropdown change — hence the generous separate rate bucket."""
    a, cfg, D, P, hw, _ = _prepare_analysis(
        request, model=model, context=context, requests=requests,
        kv_dtype=kv_dtype, tp=tp, pp=pp, ep=ep, dp_attention=dp_attention,
        instance=instance, gpu=gpu, gpu_mem_gib=gpu_mem_gib,
        gpus_per_node=gpus_per_node, mem_fraction_static=mem_fraction_static,
        fixed_overhead_gib=fixed_overhead_gib, batch_tokens=batch_tokens,
        chunk_tokens=chunk_tokens, weight_dtype=weight_dtype,
        rate_prefix="whatif", rate_limit=API_PER_HOUR * 10, rate_what="what-ifs per IP")
    return JSONResponse(engine.whatif_payload(
        a, cfg, D, P, hw["gpu"], chunk_tokens or batch_tokens, weight_dtype))


@app.get("/api/v1/catalog")
async def api_v1_catalog():
    """Hardware vocabulary for the skill: instances, GPUs, and defaults."""
    return JSONResponse({
        "engine_version": ENGINE_VERSION,
        "instances": {n: {"gpu": g, "gpus": c, "gpu_mem_gib": round(m / 1024, 1)}
                      for n, (g, c, m) in core.STATIC_INSTANCES.items()},
        "gpus": GPU_CATALOG,
        "gpu_perf": {g: {"bf16_tflops": p["bf16"], "fp8_tflops": p["fp8"],
                         "fp4_tflops": p["fp4"], "hbm_tbs": p["bw"]}
                     for g, p in core.GPU_PERF.items()},
        "kv_dtypes": list(KV_DTYPES),
        "defaults": {"context": 131_072, "requests": 16, "kv_dtype": "auto",
                     "tp": 8, "pp": 1, "instance": "p5en.48xlarge",
                     "mem_fraction_static": 0.9,
                     "fixed_overhead_gib": "tp-scaled: 0.65+0.265*(tp-1)",
                     "batch_tokens": 8192},
    })


@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse(request, "index.html", {
        "username": current_user(request),
        "dev_mode": DEV_MODE,
    })


@app.get("/stats")
async def stats(request: Request):
    username = require_user(request)
    admins = [u.strip() for u in os.environ.get("ADMIN_USERS", "").split(",") if u.strip()]
    if admins and username not in admins:
        raise HTTPException(403, "admins only")
    with db() as conn:
        users = conn.execute(
            "SELECT username, COUNT(*) n, MAX(ts) last_seen FROM access_log"
            " GROUP BY username ORDER BY n DESC"
        ).fetchall()
        actions = conn.execute(
            "SELECT action, COUNT(*) n FROM access_log GROUP BY action"
        ).fetchall()
        recent = conn.execute(
            "SELECT ts, username, action, model_id FROM access_log"
            " ORDER BY id DESC LIMIT 50"
        ).fetchall()
    return JSONResponse({
        "users": [dict(r) for r in users],
        "actions": [dict(r) for r in actions],
        "recent": [dict(r) for r in recent],
    })


init_db()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", "8000")))
